### ISSUE TITLE
how to run DIISCO in single cell data, which notebook i should to start first?

### ISSUE THREAD

**Issue by tian6067** [azizilab/DIISCO_public#6]
Hi,

This toolkit is excellent! Forgive me, I'm a newbie.

I want to use it in my own single cell dataset (scanpy dataset). but which one in  nootbok[https://github.com/azizilab/DIISCO_public/tree/main/notebooks](url), i should start first, because i don't found the scanpy dataset as input to DIISCO.  so is the gene experssion matrix (csv) as input? 

please tell me, thank you very much.

**Comment by cameronyoungpark** [comment]
The input to DIISCO is cell type proportions over time. Your single cell dataset needs to have samples sequenced at multiple time points and you need to go through your preferred clustering/annotation pipeline. The gene expression is only used in generating the prior and in post processing to predict R-L interactions. We are currently updating the package so please check back in a few weeks!
